sudo: false
language: generic
git:
  lfs_skip_smudge: true # We don't need the LFS files to build the paper.
matrix:
  include:
    - os: linux
      env: TEST_LANG='paper'
script: |
  if [[ $TEST_LANG == paper ]]
  then
    source .ci/build-paper.sh
  fi
