name: paper-maker
# description: Automagically build LaTex manuscripts and push the latest PDF back to GitHub.  Derived from andycasey's paper-maker.

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MANUSCRIPT_PATH: note/reweighting # exclude the '.tex' / '.pdf' extension!
      LATEX: pdflatex -shell-escape
      BIBTEX: bibtex
    steps:
    - uses: actions/checkout@v1
    - name: Install texlive
      run: |
        sudo apt-get install texlive texlive-publishers latexmk
    - name: Build paper
      run: |
        cd ${MANUSCRIPT_PATH%/*}
        latexmk -pdf -f ${MANUSCRIPT_PATH##*/}
    - name: Push paper
      run: |
        git checkout --orphan ${GITHUB_REF##*/}-pdf
        git rm -rf .github/
        cd ${MANUSCRIPT_PATH%/*}
        git rm -rf .
        git add -f ${MANUSCRIPT_PATH##*/}.pdf
        git -c user.name='paper-maker' -c user.email='paper-maker' commit -m "update pdf"
        git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${GITHUB_REF##*/}-pdf
