name: Build paper
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: apt-get texlive
      - name: Build doc
        run: latexmk -pdf -f note/reweighting
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: reweighting.pdf
          path: note/reweighting.pdf
